"""availability per service

Revision ID: d9626d228458
Revises: 1f00b6c2de4e
Create Date: 2026-07-11 02:40:25.850383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9626d228458'
down_revision: Union[str, Sequence[str], None] = '1f00b6c2de4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM availability_rules")
    op.add_column('availability_rules', sa.Column('service_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_availability_rules_organization_id'), table_name='availability_rules')
    op.create_index(op.f('ix_availability_rules_service_id'), 'availability_rules', ['service_id'], unique=False)
    op.drop_constraint(op.f('availability_rules_organization_id_fkey'), 'availability_rules', type_='foreignkey')
    op.create_foreign_key(None, 'availability_rules', 'services', ['service_id'], ['id'], ondelete='CASCADE')
    op.drop_column('availability_rules', 'organization_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('availability_rules', sa.Column('organization_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'availability_rules', type_='foreignkey')
    op.create_foreign_key(op.f('availability_rules_organization_id_fkey'), 'availability_rules', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_availability_rules_service_id'), table_name='availability_rules')
    op.create_index(op.f('ix_availability_rules_organization_id'), 'availability_rules', ['organization_id'], unique=False)
    op.drop_column('availability_rules', 'service_id')
    # ### end Alembic commands ###
